### ISSUE TITLE
Deploy docker app on clever-cloud

### ISSUE THREAD

**Issue by Randriamitsiry** [CleverCloud/doc.clever-cloud.com#480]
I have an application running on docker that I want to deploy on clever-cloud but it always display this error when deploying:
`Nothing listening on 0.0.0.0:8080 yet. If the deployment fails after this message, please update your configuration and redeploy.`

My docker-compose file:
```
version: '3.7'

services:
    front:
        container_name: front
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - 8081:80
        labels:
            NAME: "Signalement Front"
        networks:
            - app-network
        environment:
            - CHOKIDAR_USEPOLLING=true
        expose:
          - 8081

networks:
    app-network:
        driver: bridge
```

The Dockerfile:
```
FROM node:alpine as builder
WORKDIR /app
COPY . ./
RUN yarn install
RUN yarn run build
FROM nginx:alpine
COPY docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```
I have changed the value of CC_DOCKER_EXPOSED_HTTP_PORT to 8081 and CC_MOUNT_DOCKER_SOCKET to true
